# Python For ML - Session 4

The real world dataset can be imported into python environment through python using following keywords:

In [ ]:
# Task 1
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv")

## Revision
### Inspecting the dataset

As discussed in the last notebook, can run following operations on dataframe:
```python
df.head()      # shows the first 5 rows
df.tail(3)     # shows the last 3 rows
df.shape       # (rows, columns) — just like NumPy
df.columns     # the list of column names
df.info()      # summary: column names, data types, non-null counts
df.describe()  # summary statistics (mean, min, max, etc.) for numeric columns
```

In [ ]:
# Task 2

# Read the top 3 rows from the dataset using head() method on the dataframe
df.head(3)

# Print the shape of the dataset, no. of rows and columns
df.shape


# Print the column names of the dataframe
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [6]:
# Task 3

# Use df.info() to see the datatype of each column and the no. of not-null content
# Which column has a lot of null values?
df.info()

# Run df.describe() to view statistical values of different columns in the table (works only for numerical values)
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

## Missing Data

From using .info() method above, you can see that there are a lot of non-null values in some of the columns. That, means those columns have values that weren't entered in the data collection process. Real data comes with such kind of discrepancies you have to account for.

One of the easiest approach to deal with this problem is just to drop the dataset.

```python
df_clean = df.dropna() # Drops all rows with missing values
```

In [11]:
# Task 4
# Count the missing values in each column using isnull().sum()
df.isnull().sum()

# Create a cleaned DataFrame by dropping rows with missing values:
cleaned_df = df.dropna()

# Print the shape of the DataFrame again to see how many rows you lost due to the drop command
cleaned_df.shape
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    object
 1   island             333 non-null    object
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 20.8+ KB

## Selecting & Filtering

Pull specific column(s) by using square bracket. Multiple columns can be pulled by using another pair of square bracket similar to using a list.

```python
id_col = df["id"] # This will pull column named id
id_and_name = df[["id", "student_name"]] # This will pull id and name
```

```python
passed_students = df[df["score"]>40] # This will filter out students with score more than 40
```

Multiple conditions can be combined as follows:

```python
first_division = df[(df["score"]>70) & (df["score"]<80)]
```

Use & for AND logic and | for OR logic

In [18]:
# Task 5
# Print just the "species" column
species_column = df['species']
print(species_column)

# Print the "species", "island", and "body_mass_g" columns together
multi_column = df[['species', 'island', 'body_mass_g']]
multi_column

table_describe = multi_column.describe()
table_describe

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: object

       body_mass_g
count   342.000000
mean   4201.754386
std     801.954536
min    2700.000000
25%    3550.000000
50%    4050.000000
75%    4750.000000
max    6300.000000

In [ ]:
# Print only the penguins heavier than 4500 grams
heavier_penguins = df[df['body_mass_g'] > 4500]
heavier_penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,MALE
39,Adelie,Dream,39.8,19.1,184.0,4650.0,MALE
45,Adelie,Dream,39.6,18.8,190.0,4600.0,MALE
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,MALE
101,Adelie,Biscoe,41.0,20.0,203.0,4725.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [22]:
# Print only the penguins from the island "Biscoe"
df[df['island'] == 'Biscoe']

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,FEMALE
21,Adelie,Biscoe,37.7,18.7,180.0,3600.0,MALE
22,Adelie,Biscoe,35.9,19.2,189.0,3800.0,FEMALE
23,Adelie,Biscoe,38.2,18.1,185.0,3950.0,MALE
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0,MALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
# Print penguins that are BOTH heavier than 4000g AND of species "Gentoo"
df[(df['body_mass_g'] > 4000) & (df['species'] == 'Gentoo')]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
220,Gentoo,Biscoe,46.1,13.2,211.0,4500.0,FEMALE
221,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,MALE
222,Gentoo,Biscoe,48.7,14.1,210.0,4450.0,FEMALE
223,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,MALE
224,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [25]:
# Print penguins from EITHER "Biscoe" OR "Dream" island
df[(df['island'] == 'Biscoe') | (df['island'] == 'Dream')]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,FEMALE
21,Adelie,Biscoe,37.7,18.7,180.0,3600.0,MALE
22,Adelie,Biscoe,35.9,19.2,189.0,3800.0,FEMALE
23,Adelie,Biscoe,38.2,18.1,185.0,3950.0,MALE
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0,MALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

## Adding columns

You can assign to column that doesn't exist in the dataframe to create new column. Usually newer columns are created using values of old columns. For eg:

```python
df["taxes"] = df["salary"]*0.25 #Taxes doesn't exist in the dataframe yet, salary does
```

In [31]:
# Task 6

# Add a column "body_mass_kg" that converts body_mass_g into kilograms
df['body_mass_kg'] = df['body_mass_g'] / 1000
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_kg,is_heavy
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,3.75,False
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,3.80,False
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,3.25,False
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN,False
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,3.45,False

In [32]:
# Add a boolean column "is_heavy" that is True when body_mass_g is above 4500
df['is_heavy'] = df['body_mass_g'] > 4500
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_kg,is_heavy
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,3.75,False
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,3.80,False
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,3.25,False
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN,False
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,3.45,False

In [33]:
# Print the first few rows to check your new columns
df.head(4)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_kg,is_heavy
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,3.75,False
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,3.80,False
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,3.25,False
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN,False

## Group by

Just like GROUP BY in SQL, pandas allows you to group rows by certain category to obtain aggregated information.

```python
df.groupby("location")["salary"].mean() #Gives average salary per location
df.groupby("location").size() # How many students or person per location
```

In [36]:
# Task 7
# Find the average body_mass_g for each species
df.groupby('species')['body_mass_g'].mean()

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

In [37]:
# Find the average flipper_length_mm for each species
df.groupby('species')['flipper_length_mm'].mean()

species
Adelie       189.953642
Chinstrap    195.823529
Gentoo       217.186992
Name: flipper_length_mm, dtype: float64

In [38]:
# Count how many penguins are on each island (groupby + size)
df.groupby('island').size()

island
Biscoe       168
Dream        124
Torgersen     52
dtype: int64

In [39]:
# Find the maximum body_mass_g for each species
df.groupby('species')['body_mass_g'].max()

species
Adelie       4775.0
Chinstrap    4800.0
Gentoo       6300.0
Name: body_mass_g, dtype: float64

## Value counts

Value count provides a fast way to see how a category is distributed.

```python
df["location"].value_counts()
```

In [43]:
# Task 8
# Use value_counts() to see how many penguins of each species there are
df['species'].value_counts()

# Use value_counts() on the "island" column
df['island'].value_counts()

# Use value_counts() on "sex" — notice how the missing values you dropped affect this
df['sex'].value_counts()

sex
MALE      168
FEMALE    165
Name: count, dtype: int64

## Combining it all

All of these concepts and features of df can be used to answer complex questions about the datset. You can use them to answer the questions below.

In [44]:
# 1. Which species has the highest average body mass? use .idxmax() to return highest index value from grouped values.
df.groupby('species')['body_mass_g'].mean().idxmax()

'Gentoo'

In [45]:
# 2. On which island do penguins have the longest average flipper length?
df.groupby('island')['flipper_length_mm'].mean().idxmax()

'Biscoe'

In [51]:
# 3. Are Gentoo penguins heavier on average than Adelie penguins?

adelie_avg = df[df['species'] == 'Adelie']['body_mass_g'].mean()
gentoo_avg = df[df['species'] == 'Gentoo']['body_mass_g'].mean()

print("Adelie average:", adelie_avg)
print("Gentoo average:", gentoo_avg)
print("Gentoo heavier?", gentoo_avg > adelie_avg)

Adelie average: 3700.662251655629
Gentoo average: 5076.016260162602
Gentoo heavier? True

In [55]:
# 4. How many penguins weigh more than the overall average body mass?
#    (hint: compute the mean first, then filter)
overall_avg = df['body_mass_g'].mean()
overall_avg
df[df['body_mass_g'] > overall_avg]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_kg,is_heavy
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,MALE,4.675,True
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,4.250,False
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,MALE,4.400,False
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,MALE,4.500,False
39,Adelie,Dream,39.8,19.1,184.0,4650.0,MALE,4.650,True
...,...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE,4.925,True
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE,4.850,True
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE,5.750,True
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE,5.200,True
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE,5.400,True

In [57]:
# 5. For each species, what is the average mass of just the penguins on Biscoe island? 
# (hint: filter first, then groupby)
df[df['island'] == 'Biscoe'].groupby('species')['body_mass_g'].mean()

species
Adelie    3709.659091
Gentoo    5076.016260
Name: body_mass_g, dtype: float64

# Well Done!