# Python For ML - Session 3

## Numpy

Numpy is a python library used for numerical computing. A lot of machine learning libraries are built on top of this library. Its core object is `ndarray` (n-dimensional array), it is like a python list but far more powerful.

You import numpy with following syntax:

```python
import numpy as np
```

You can create an numpy array from a regular list:

```python
arr = np.array([1,2,3,4,5])
```

In [ ]:
# Task 1

# Import numpy with the alias np
import numpy as np

# Create a numpy array from a list of numbers and print it
arr = np.array([10, 20, 30, 40, 50])
print(arr)

# Use the type function to check the type of the numpy variable you created
print(type(arr))

# The type function is just type()

[10 20 30 40 50]
<class 'numpy.ndarray'>

### Creating arrays

Numpy has a number of built-in methods that makes creating certain kind of arrays simple.

```python
np.zeros(5) #Creates an array of 5 zeroes
np.ones(3) #Creates an array of 3 ones
np.arange(0,10,2) #Like the range() function with the for loop 
# Creates an array starting from 0 to 10 with increament of 2 each turn
# output: [0 2 4 6 8]
np.linspace(0,1,5) #5 evenly spaced values from 0-1
# output: [0. 0.25 0.5 0.75 1. ]

In [5]:
# Task 2
# Create an array of ten zeros and print it
zeros_arr = np.zeros(10)
print(zeros_arr)

# Create an array of values from 0 to 20 (exclusive) stepping by 5, and print it
array = np.arange(0, 20, 5)
print(array)

# Use linspace to create 6 evenly spaced values between 0 and 100, and print it
linspace_arr = np.linspace(0, 100, 6)
print(linspace_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0  5 10 15]
[  0.  20.  40.  60.  80. 100.]

### Array shape and dimension

Numpy arrays and python lists can both be nested. However, python list doesn't enforce uniformity.

```python
nested_list = [[1,2,3], [1,2]] #Nested lists of varying length
```

Numpy forces multidimensional arrays to be uniform.

```python
matrix = np.array([[1,2,3], [4,5,6]]) # Nested array of uniform length 3
```

This is essentially a matrix (a grid of rows and columns), which is used and seen regularly in Machine Learning.

np.array provides multiple methods to work with multidimensional arrays:

```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(matrix.shape)  # output: (2, 3) -> returns a tuple of rows and columns of the array
print(matrix.ndim)   # output: 2 -> returns a number of dimensions, the no. of dimensions depend on how nested the array is
print(matrix.size)   # output: 6 -> returns total no. of elements

```

In [7]:
# Task 3
# Create the following 2D array (3 rows, 3 columns):
# 1 2 3
# 4 5 6
# 7 8 9

two_d_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(two_d_arr)
# Print its shape
print(two_d_arr.shape)

# Print how many dimensions it has
print(two_d_arr.ndim)

# Print the total number of elements
print(two_d_arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9

### Indexing and Slicing

Indexing and slicing work in numpy arrays just like they do in python lists. The difference is that numpy arrays can have multiple dimensions, so you separate the index for each dimension with a comma.

For example, `arr[row, column]` selects a single element, and you can slice within each dimension too: `arr[0:2, 1:3]` takes rows 0–1 and columns 1–2.

```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix[0, 0])   # output: 1 -> first row, first column
print(matrix[1, 2])   # output: 6 -> second row, third column
print(matrix[0])      # output: [1 2 3] -> the entire first row
print(matrix[:, 0])   # output: [1 4 7] -> the entire first column
```

The `:` means "everything along this dimension." So `matrix[:, 0]` reads as "every row, column 0."

In [12]:
import numpy as np
# Task 4
# Given the array below:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

# Print the element at the second row, third column (should be 60)
print(data[1, 2])

# Print the entire second row
print(data[1])

# Print the entire first column
print(data[:, 0])

# Use slicing to print the top-left 2x2 block (10, 20, 40, 50)
print(data[0:2, 0:2])

60
[40 50 60]
[10 40 70]
[[10 20]
 [40 50]]

### Vectorized operations

With regular python lists, if you have a list of numbers, and you want to perform some sort of calculations with all the values in the list, you have do a for each loop, navigate through the list, do the calculations for each element and store them.

This is where numpy shines:

```python
num_array = np.array([10,20,30,40])

num_array = num_array * 3 # This multiplies all the element of the array by 3
num_array = num_array ** 3 # This gives you an array with all the element's power raised by 3
```

If you have arrays of valid dimension, you can even do calculations between the arrays using operators.

```python
num_array_1 = np.array([1,2,3])
num_array_2 = np.array([4,5,6])

num_array_3 = num_array_1 + num_array_2 # output will  be [5 7 9]
```

Furthermore, since numpy vectorized operations are implemented using C code, these operations work on contiguous numeric values of the same type and are more efficient than looping over a list in python.

In [18]:
# Task 5
# Create an array of values 1 through 10 (use arange)
arr = np.arange(1,11)
print(arr)

# Multiply every element by 3 and print the result
arr_multiplied = arr * 3
print(arr_multiplied)

# Square every element and print the result
arr_squared = arr ** 2
print(arr_squared)

# Create a second array of the same length and add the two arrays together
arr2 = np.arange(11, 21)
arr_sum = arr + arr2
print(arr_sum)

[ 1  2  3  4  5  6  7  8  9 10]
[ 3  6  9 12 15 18 21 24 27 30]
[  1   4   9  16  25  36  49  64  81 100]
[12 14 16 18 20 22 24 26 28 30]

### Useful array functions

numpy provides functions that summarize an entire array.

```python
arr = np.array([4, 8, 15, 16, 23, 42])

print(arr.sum())    # output: 108
print(arr.mean())   # output: 18.0  (the average)
print(arr.max())    # output: 42
print(arr.min())    # output: 4
print(arr.std())    # output: standard deviation
```

In [20]:
# Task 6
# Given the array of exam scores below:
scores = np.array([72, 88, 95, 60, 78, 90, 85])

# Print the highest score
print(np.max(scores))

# Print the lowest score
print(np.min(scores))

# Print the average (mean) score
print(np.mean(scores))

# Print the sum of all scores
print(np.sum(scores))

95
60
81.14285714285714
568

## Pandas

Numpy is great for working with raw numerical arrays and multi dimensional arrays.

Pandas serves the role of working with tabular data with distinct column labels. Think of it like actively interacting with a database table through python syntax.

It is used for loading, cleaning, and exploring the datasets before feeding them into a model.

It can be imported as follows:

```python
import pandas as pd
```

Pandas has 2 main objects:

1. Series: It is like a single column of values extracted from a table. Eg: A series of student_names from a student table.

2. DataFrame: It is the entire table with column name and multiple columns. It can be thought of as a dictionary, with key being column name and value being a series.

In [ ]:
# Task 7
# Import pandas with the alias pd
import pandas as pd

# Create a Series from the list [10, 20, 30, 40] and print it
series = pd.Series([10, 20, 30, 40])
print(series)

# (use pd.Series(...))

0    10
1    20
2    30
3    40
dtype: int64

## Creating a dataframe

Dataframe can be created in multiple ways. Creating through a dictionary is one of the ways:

```python
fruit_data = {
  "fruit_id" : [1, 2, 3, 4, 5, 6],
  "fruit_name": ["Apple", "Mango", "Orange", "Pear", "Grape", "Guava"],
  "fruit_price": [10, 20, 23, 13, 18, 19],
  "fruit_stock": [10, 39, 29, 11, 20, 23]
}

df = pd.DataFrame(fruit_data)
print(df)
```

The structure here is a list of dictionary. DataFrame takes this dictionary and displays it in a tabular ordered format.

In [27]:
# Task 8
# Create a DataFrame from the following data:
student_data = {
    "student": ["Alice", "Bob", "Charlie"],
    "marks": [85, 90, 78],
    "passed": [True, True, False]
}

df = pd.DataFrame(student_data)
df

# - a column "student" with three names of your choice
# - a column "marks" with three numerical values
# - a column "passed" with three boolean values (True/False)

   student  marks  passed
0    Alice     85    True
1      Bob     90    True
2  Charlie     78   False

### Inspecting a DataFrame

A real world dataset can have thousands of rows and dozens of columns. You can use these methods to inspect the data.

```python
df.head()      # shows the first 5 rows
df.tail(3)     # shows the last 3 rows
df.shape       # (rows, columns) — just like NumPy
df.columns     # the list of column names
df.info()      # summary: column names, data types, non-null counts
df.describe()  # summary statistics (mean, min, max, etc.) for numeric columns
```

In [31]:
# Task 9
# Run the cell below to create a sample DataFrame:
df = pd.DataFrame({
    "name":   ["Asha", "Bikram", "Chandra", "Deepak", "Esha"],
    "age":    [22, 25, 23, 28, 21],
    "score":  [88, 72, 95, 60, 79],
    "city":   ["Kathmandu", "Pokhara", "Lalitpur", "Kathmandu", "Pokhara"]
})

df

# Print the first 3 rows using head()
df.head(3)

# Print the shape of the DataFrame
df.shape

# Print the column names
df.columns

# Use describe() to print summary statistics
df.describe()

             age      score
count   5.000000   5.000000
mean   23.800000  78.800000
std     2.774887  13.663821
min    21.000000  60.000000
25%    22.000000  72.000000
50%    23.000000  79.000000
75%    25.000000  88.000000
max    28.000000  95.000000

### Selecting columns and rows

You select a single column using square brackets with the column name (this returns a Series). For multiple columns, pass a *list* of names.

```python
df["age"]              # one column (a Series)
df[["name", "age"]]    # two columns (returns a dataframe consisting of "name" and "age"
```

To select rows by a condition, you can use boolean masking:

```python
df[df["age"] > 24]     # only rows where age is greater than 24 is selected
```

In [36]:
# Task 10
# Using the df from Task 9:
df
# Print just the "name" column
df["name"]

# Print the "name" and "score" columns together
df[["name", "score"]]

# Print only the rows where score is greater than 75
df[df["score"] > 75]

# Print only the rows where city is "Kathmandu"
df[df["city"] == "Kathmandu"]

     name  age  score       city
0    Asha   22     88  Kathmandu
3  Deepak   28     60  Kathmandu

### Adding and modifying columns

You can create a new column simply by assigning to a column name that doesn't exist yet, very similar to adding a key to a dictionary.

Operations can be applied to the whole column at once (vectorized, like numpy).

```python
df["age_in_5_years"] = df["age"] + 5     # new column from a calculation
df["passed"] = df["score"] >= 70         # new boolean column from a condition
```

In [42]:
# Task 11
# Using the df from Task 9:
df
# Add a new column "score_out_of_50" that is each score divided by 2
df["score_out_of_50"] = df["score"] / 2
df

# Add a new boolean column "distinction" that is True when score is 90 or above
df["distinction"] = df["score"] >= 90

# Print the updated DataFrame
df

      name  age  score       city  score_out_of_50  distinction
0     Asha   22     88  Kathmandu             44.0        False
1   Bikram   25     72    Pokhara             36.0        False
2  Chandra   23     95   Lalitpur             47.5         True
3   Deepak   28     60  Kathmandu             30.0        False
4     Esha   21     79    Pokhara             39.5        False

### Grouping and aggregating

A very common task is to group rows by some category and compute a summary for each group. For example, the average score per city. This is done with `groupby()`. This is similar to 'GROUP BY' in SQL.

```python
df.groupby("city")["score"].mean()   # average score for each city
df.groupby("city").size()            # number of rows in each city
```

`groupby` splits the table into groups, applies a calculation (like `mean`, `sum`, `max`) to each group, and combines the results.

In [49]:
# Task 12
# Using the df from Task 9:
print(df)
# Group by "city" and find the average age for each city
df.groupby("city")["score"].mean()

# Group by "city" and find the highest score in each city
df.groupby("city")["score"].max()

# Group by "city" and count how many students are in each city
df.groupby("city")["name"].count()

      name  age  score       city  score_out_of_50  distinction
0     Asha   22     88  Kathmandu             44.0        False
1   Bikram   25     72    Pokhara             36.0        False
2  Chandra   23     95   Lalitpur             47.5         True
3   Deepak   28     60  Kathmandu             30.0        False
4     Esha   21     79    Pokhara             39.5        False

city
Kathmandu    2
Lalitpur     1
Pokhara      2
Name: name, dtype: int64

## More on NumPy

**If you've finished all the tasks above, read through these and try them out in a new cell.**

### Reshaping arrays

You can rearrange the same data into a different shape without changing the values. The total number of elements has to stay the same (a 12-element array can become 3×4, 4×3, 2×6, etc.).

```python
arr = np.arange(12)        # [0 1 2 3 4 5 6 7 8 9 10 11]
arr.reshape(3, 4)          # 3 rows, 4 columns
arr.reshape(4, 3)          # 4 rows, 3 columns
arr.reshape(2, -1)         # 2 rows, NumPy figures out the columns (6)
```

The -1 shortcut can be really handy as numpy basically handles the remaining dimensions so that it matches well the the array that you have provided.

### Aggregating along an axis

For a 2D array, `.sum()` or `.mean()` on its own collapses the whole thing into one number. But often you want a sum *per row* or *per column*. That's what the `axis` argument is for.

```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix.sum()           # 21 -> everything
matrix.sum(axis=0)     # [5 7 9] -> sum down each column
matrix.sum(axis=1)     # [6 15]  -> sum across each row
```

The axis=0 basically means that the sum crushes the axis 0. The above matrix has (2,3) as its dimensions, 0 axis here means the first element, or the rows. So it removes the rows  to create a sum, giving [5 7 9] as the values.

### Broadcasting

Earlier you added a single number to a whole array (`arr + 10`). Numpy can also use a smaller array with a bigger one to perform operations, as long as the shapes are compatible. Numpy stretches the smaller array to match the larger array. This is called *broadcasting*.

```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

row = np.array([10, 20, 30])

matrix + row    # row is added to every row of the matrix:
# [[11 22 33]
#  [14 25 36]]
```

Broadcasting is a crucial feature of numpy, and is very important in ML.

### Random numbers

Numpy can generate random arrays, which you'll need for things like initialising matrices and arrays.

```python
np.random.seed(42)            # using seed makes random results deterministic/predictable
np.random.rand(3)             # 3 random floats between 0 and 1
np.random.randint(0, 10, 5)   # 5 random integers from 0 to 9
np.random.randn(3)            # 3 values from a normal (bell-curve) distribution
```

Using seed can be helpful as it means you get the same "random" numbers every run, which makes bugs reproducible.

### A few more handy functions

```python
arr = np.array([3, 1, 4, 1, 5, 9, 2])

np.sort(arr)        # returns a sorted copy
arr.argmax()        # index of the largest value (here: 5)
arr.argmin()        # index of the smallest value
np.unique(arr)      # the distinct values: [1 2 3 4 5 9]
np.clip(arr, 2, 5)  # forces every value into the range [2, 5]
```

`argmax` is worth remembering as it will come up later in ML while picking the output value from a model to create prediction.

## More on pandas

**If you've finished all the tasks above, read through these and try them out in a new cell.**

Use this sample DataFrame for the examples below:

```python
df = pd.DataFrame({
    "name":   ["Asha", "Bikram", "Chloe", "Deepak", "Esha", "Farhan"],
    "age":    [22, 25, 23, 28, 21, 26],
    "score":  [88, 72, 95, 60, 79, 91],
    "city":   ["Kathmandu", "Pokhara", "Lalitpur", "Kathmandu", "Pokhara", "Lalitpur"]
})
```

### Selecting rows by label vs. position: .loc and .iloc

So far you've selected columns. To select specific *rows*, pandas gives you two tools:

```python
df.loc[0]            # the row with index label 0 (first row)
df.iloc[0]           # the row at position 0 (also the first row, by position)

df.loc[0, "name"]    # a single cell: row 0, column "name"
df.iloc[0:3]         # the first three rows (by position, like list slicing)
```

The difference matters once your index isn't just 0, 1, 2... `loc` works by *label*, `iloc` works by *position*. For now they often look the same, but the distinction becomes important with real data.

### Sorting

```python
df.sort_values("score")                      # sort rows by score, ascending
df.sort_values("score", ascending=False)     # highest score first
df.sort_values(["city", "score"])            # sort by city, then by score within each city
```

### Combining conditions when filtering

You can filter on more than one condition. Each condition goes in its own parentheses, joined with `&` (and) or `|` (or).

```python
df[(df["score"] > 80) & (df["age"] < 25)]    # high score AND young
df[(df["city"] == "Pokhara") | (df["city"] == "Lalitpur")]   # either city
```

Note it's `&` and `|`, not the words `and` / `or` as in normal python. The syntax is different.

### value_counts: how many of each?

A quick way to count how often each value appears in a column:

```python
df["city"].value_counts()
# Kathmandu    2
# Pokhara      2
# Lalitpur     2
```

This can be useful to run on real world dataset to see how your dataset is distributed.

### using `apply` to run a function on the column

When a calculation is too complex for a simple `df["col"] * 2`, you can write a function and apply it to a column.

```python
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 70:
        return "B"
    else:
        return "C"

df["grade"] = df["score"].apply(grade)
```

`apply` runs the function you have defined for all rows of the columns that you have specified.

### Handling missing data

Real datasets have gaps. pandas represents a missing value as `NaN` (Not a Number), and gives you tools to deal with it.

```python
df.isnull()           # True wherever a value is missing
df.isnull().sum()     # count of missing values per column
df.dropna()           # drop any row that has a missing value
df.fillna(0)          # replace missing values with 0
```

These methods are really crucial for cleaning the data as the real world datas have a lot of missing values, which you want to not include as models don't handle them very well.

# Well Done!